name: Build and Release
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.setenv.outputs.version }}
      revision: ${{ steps.setenv.outputs.revision }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ag-sdc/libcompat
          ref: main

      - name: Set up environment
        id: setenv
        run: |
          VERSION=$(cat VERSION)

          version_cmp() {
            local a=${1#v} b=${2#v}
            a=${a%-*}.
            b=${b%-*}.
            while [ "$a" ] && [ "$b" ]; do
              [[ ${a%%.*} -gt ${b%%.*} ]] && return 0
              a=${a#*.}
              b=${b#*.}
            done
            return 1
          }

          set_version() {
            LATEST_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/tags?per_page=1" | jq -r '.[0].name')
            if [ "$LATEST_TAG" = "null" ] || [ "$LATEST_TAG" = "" ]; then
              export REVISION=1
              return
            fi

            if version_cmp $VERSION $LATEST_TAG; then
              export REVISION=1
              return
            fi

            TAG_REV=${LATEST_TAG#*-}
            if [ ! "$TAG_REV" ]; then
              export REVISION=1
              return
            fi
            
            export REVISION=$((TAG_REV + 1))
          }

          set_version

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "REVISION=$REVISION" >> "$GITHUB_ENV"
          
          # Export to job output
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "revision=$REVISION" >> "$GITHUB_OUTPUT"
    
  build:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.setup.outputs.version }}
      revision: ${{ needs.setup.outputs.revision }}
    permissions:
      contents: read
    container:
      image: ghcr.io/shadichy/cachyos-android-ci:latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [32, 33, 34, 35]
        ndk: [/opt/android-ndk]
        x86-64-level: [v2, v3, v4]
        include:
          - api-level: 36
            ndk: /opt/android-ndk-beta
            x86-64-level: v2
          - api-level: 36
            ndk: /opt/android-ndk-beta
            x86-64-level: v3
          - api-level: 36
            ndk: /opt/android-ndk-beta
            x86-64-level: v4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ag-sdc/libcompat
          ref: main

      - name: Checkout makeapex
        uses: actions/checkout@v6
        with:
          repository: ag-sdc/makeapex
          ref: main
          path: makeapex

      - name: Checkout platform
        uses: actions/checkout@v6

      - name: Set up toolchain
        run: |
          export TOOLCHAIN="${{ matrix.ndk }}/toolchains/llvm/prebuilt/linux-x86_64"
          export API=${{ matrix.api-level }}
          export NDK=${{ matrix.ndk }}
          export TARGET=x86_64-linux-android

          case "${{ matrix.x86-64-level }}" in
            v2) ARCH_FLAGS="-march=x86-64-v2 -mtune=generic" ;;
            v3) ARCH_FLAGS="-march=x86-64-v3 -mtune=generic -mavx -mavx2 -mf16c -mfma -mbmi -mbmi2 -mlzcnt" ;;
            v4) ARCH_FLAGS="-march=x86-64-v4 -mtune=generic -mavx512f -mavx512bw -mavx512cd -mavx512dq -mavx512vl" ;;
          esac

          COMMON_FLAGS="-O2 -fPIC -DANDROID -D__ANDROID_API__=${API} -ffunction-sections -fdata-sections ${ARCH_FLAGS}"

          echo "NDK=${NDK}" >> "$GITHUB_ENV"
          echo "API=${API}" >> "$GITHUB_ENV"
          echo "CC=${TOOLCHAIN}/bin/${TARGET}${API}-clang" >> "$GITHUB_ENV"
          echo "CXX=${TOOLCHAIN}/bin/${TARGET}${API}-clang++" >> "$GITHUB_ENV"
          echo "AR=${TOOLCHAIN}/bin/llvm-ar" >> "$GITHUB_ENV"
          echo "NM=${TOOLCHAIN}/bin/llvm-nm" >> "$GITHUB_ENV"
          echo "RANLIB=${TOOLCHAIN}/bin/llvm-ranlib" >> "$GITHUB_ENV"
          echo "STRIP=${TOOLCHAIN}/bin/llvm-strip" >> "$GITHUB_ENV"
          echo "CFLAGS=${COMMON_FLAGS}" >> "$GITHUB_ENV"
          echo "CXXFLAGS=${COMMON_FLAGS}" >> "$GITHUB_ENV"
          echo "LDFLAGS=-Wl,--gc-sections" >> "$GITHUB_ENV"

      - name: Build APEX package
        run: |
          sed -i "s/^pkgrel=.*/pkgrel=${{ needs.setup.outputs.revision }}/" APEXBUILD

          export PATH=$PATH:$(pwd)/makeapex/src
          find makeapex -type f
          makeapex.sh

          # Rename output apex files to uniquely identify them for upload
          GITHUB_REPOSITORY="${{ github.repository }}"
          for apex in *.apex; do
            basename=${GITHUB_REPOSITORY#*/}
            case "$apex" in *-headers-*.apex) basename=$basename-headers ;; esac
            mv "$apex" "${basename}-api${{ matrix.api-level }}-x86_64-${{ matrix.x86-64-level }}.apex"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libcompat-apex-api${{ matrix.api-level }}-x86_64-${{ matrix.x86-64-level }}.tar.gz
          path: ./*.apex
          archive: false

  release:
    needs: build
    if: >
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/devel' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Fetch APEX Artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./tmp_artifacts/

      - name: Flatten artifacts
        run: |
          mkdir -p released-files
          find tmp_artifacts -type f -name "*.apex" -exec cp -t released-files {} +
          rm -rf tmp_artifacts

      - name: Calculate release metadata
        id: setmeta
        run: |
          TAG=${{ needs.build.outputs.version }}-${{ needs.build.outputs.revision }}
          IS_PRERELEASE=false
          if [ '${{ github.event.inputs.is_prerelease }}' = 'true' ] || \
             [ '${{ github.ref }}' = 'refs/heads/dev' ] || \
             [ '${{ github.ref }}' = 'refs/heads/devel' ] || \
             [ '${{ github.ref }}' = 'refs/heads/develop' ]; then
            IS_PRERELEASE=true
            TAG=${TAG}-dev
          fi

          echo "release_date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "is_prerelease=${IS_PRERELEASE}" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.setmeta.outputs.tag }}
          name: Release ver ${{ steps.setmeta.outputs.tag }} at ${{ steps.setmeta.outputs.release_date }}
          prerelease: ${{ steps.setmeta.outputs.is_prerelease }}
          files: released-files/*
